int cpu_rnnt(THFloatTensor *trans_acts,
                THFloatTensor *pred_acts,
                THIntTensor *labels,
                THIntTensor *input_lengths,
                THIntTensor *label_lengths,
                THFloatTensor *costs,
                THFloatTensor *trans_grad,
                THFloatTensor *pred_grad,
                int blank_label,
                int num_threads);