int gpu_rnnt(THCudaTensor *trans_acts,
                THCudaTensor *pred_acts,
                THIntTensor *labels,
                THIntTensor *input_lengths,
                THIntTensor *label_lengths,
                THFloatTensor *costs,
                THCudaTensor *trans_grad,
                THCudaTensor *pred_grad,
                int blank_label,
                int num_threads);